Repository Mobeom/MoBeom, pull requests merged in 2021-05, with the labels that each got.

#25 Feature/23 health center
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/tensorflow/lite/examples/classification/Presentation/HealthCenterActivity/HealthCenterActivity.java
  app/src/main/java/org/tensorflow/lite/examples/classification/Presentation/MainActivity/MainActivity.java
  app/src/main/res/drawable/ic_baseline_gps_fixed_24.xml
  app/src/main/res/layout/activity_health_center.xml
Labels: enhancement, fix

#31 #15 마스크 미착용시 경고성 음성 메세지 출력 및 마스크 착용 여부 인터페이스에 출력
  app/src/main/java/org/tensorflow/lite/examples/classification/Presentation/MaskDetectionActivity/CameraActivity.java
  app/src/main/java/org/tensorflow/lite/examples/classification/Presentation/MaskDetectionActivity/ClassifierActivity.java
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/raw/hun.mp3
  build.gradle
Labels: enhancement

#34 feature/19-SplashActivity
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/tensorflow/lite/examples/classification/Presentation/SplashActivity/FirstFragment.java
  app/src/main/java/org/tensorflow/lite/examples/classification/Presentation/SplashActivity/FragmentAdapter.java
  app/src/main/java/org/tensorflow/lite/examples/classification/Presentation/SplashActivity/SecondFragment.java
  app/src/main/java/org/tensorflow/lite/examples/classification/Presentation/SplashActivity/SplashActivity.java
  app/src/main/java/org/tensorflow/lite/examples/classification/Presentation/SplashActivity/ThirdFragment.java
  app/src/main/res/drawable/ic_masks_24_olive.xml
  app/src/main/res/drawable/ripple_basic.xml
  app/src/main/res/drawable/shape_use_button.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/layout/fragment_third.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/xml/fragment_third_xml_constraintlayout_scene.xml
  app/src/main/res/xml/fragment_third_xml_constraintlayout_scene2.xml
Labels: enhancement

#39 [REFACTOR] (#38) - WarningVoice를 기계 음성으로 변경
  app/src/main/res/raw/hun.mp3
Labels: fix
